### ISSUE TITLE
Creazione account instagram

### ISSUE THREAD

**Issue by mancusoa74** [ittagnelli/ats#21]
Si richiede di creare un account instagram per ATS.
Usare l'email istituzionale ats@istitutoagnelli.it

Usare il logo ufficiale di ATS

**Consegna: 6/10/2021**

**Comment by Alexandru-Chindris** [comment]
@mancusoa74 
Professore per la creazione del account Instagram necessitiamo delle credenziali del account "ats@istitutoagnelli.it". L'iscrizione a Instagram prevede la verifica del proprio account

**Comment by Alexandru-Chindris** [comment]
Al momento la creazione del account instagram è sospesa per impossibilità di verifica dell' email ( ats@isititutoagnelli.it ).
Scriverò personalmente a Michele Dettoni per rivere maggiori informazioni in merito a questo problema.
Fino a prossimo aggiornamento rimuovo la tag "in progress"
