### ISSUE TITLE
Creazione logo ATS

### ISSUE THREAD

**Issue by mancusoa74** [ittagnelli/ats#3]
Creare un logo per ATS is formato vettoriale SVG

Il logo proposto inizialmente con il pinguino stilizzato va benissimo.
Il logo deve essere semplice in modo che possa successivamente essere stampato su carta, su tessuto o altri supporti

Se include dei colori, che abbia un richiamo al rosso uggiciale agnelli #ac1819

Fornire 3 loghi alternativi, da cui scegliere quello finale

**Consegna 29/9/2021**

Allego logo attuale come linea guida
![image](https://user-images.githubusercontent.com/2828449/134821428-676521f3-557b-4910-8d02-bda1263706cd.png)

**Comment by mancusoa74** [comment]
Dove sono i logo? Allegali a questa issue per poterla completare e poi chiudere

**Comment by Alexandru-Chindris** [comment]
Non riesco ad allegare qui i loghi
![Creazione logo ATS · Issue #3 · ittagnelli_ats - Brave 30_09_2021 22_23_37 (2)](https://user-images.githubusercontent.com/89776299/135525238-c8247d49-761a-44fa-af44-6d57adee36ed.png)

**Comment by mancusoa74** [comment]
ok potevi inserire il formato jpg del logo :)
