### ISSUE TITLE
Invio email contatti

### ISSUE THREAD

**Issue by mancusoa74** [ittagnelli/ats#4]
Nel portale ATS alla sezione *Contatti*. l'utente può inviare un messaggio di richiesta di supporto ad ATS

Utilizzando i servizi:
- https://sendgrid.com/g
- https://smtpjs.com/

Scrivere una funzione in JS che invii un email formattata contenente i campi presenti nella sezione contati del portale ATS
Modificare anche il portale in modo che la mail venga inviata alla pressione del pulsante *INVIA RICHIESTA*

**Consegna: 30/09/21**

**Comment by Dario-Ruggieri** [comment]
Buongiorno professore,
come già sa siamo riusciti (con il suo aiuto) a far funzionare la sezione dei contatti per l'invio dell'email. Inoltre abbiamo deciso di aggiungere un controllo che verifichi se tutti i campi sono stati completati e quindi se possiamo stampare l'alert "Messaggio inviato con successo" oppure "Errore durante l'invio del messaggio, riprovare". Ci siamo accorti però che se message rimane vuoto, al suo interno è comunque presente la stringa "OK"
Qua l'immagine che mostra quanto detto sopra:
![image](https://user-images.githubusercontent.com/89417736/135709510-fcf29d65-0abf-40b9-9dc5-2a225b6c92d4.png)

Nella verifica è quindi necessario verificare se il messaggio contiene "OK" il che indica che la casella del messaggio è vuota. Ciò però non permette ovviamente di mettere come messaggio "OK", anche se si può trascurare perché è relativamente inutile.

Può andar bene?
Nel caso non fosse chiaro possiamo una pull request con il codice così che possa essere analizzato.

Il gruppo DEV.

@mancusoa74 @Pierpaolo-QuijadaGomez @Federico-Pomba @Francesco-Zaina1 @Marco-Garabello @Simone-Laudani

**Comment by mancusoa74** [comment]
ok apporvata
