### ISSUE TITLE
Bug Visivo

### ISSUE THREAD

**Issue by Sebastiano-Racca** [ittagnelli/ats#63]
Nella home del sito è presente un bug visivo:
La freccia per tornare su non viene visualizzata correttamente nel footer della pagina.

![bug](https://github.com/ittagnelli/ats/assets/84769196/cb8291d8-2e94-4b6e-a392-1eaa1f13a6ca)

**Comment by profmancusoa** [comment]
@Alberto-Mastroianni mandami la PR quando hai risolto. grazie

**Comment by profmancusoa** [comment]
ottimo
